### ISSUE TITLE
incorrect paths

### ISSUE THREAD

**Issue by moesphemie** [ines/pretty-harp-jade-skeleton#2]
my compiled website doesn't work. When i open the index in the /www-folder, i get an unstyled and not working page. any suggestions?

**Comment by ines** [comment]
It's hard to say for sure without seeing it, but my bet is that it's the root-relative paths, i.e. `/assets/css` and so on. This is sort of intentional and the way I usually prefer to write my paths – but ultimately, it's a question of which style you prefer and what's most practical for you. 

When preview the site locally using `harp server`, the paths work fine because the assets folder is indeed in the root directory (`localhost`). Same if you upload the compiled site to yourdomain.com. But if you're just opening the index.html in the /www folder, it looks for the assets at the very root, so like, your hard drive.

If you want to use relative paths instead, just remove the leading `/` from the `/asset/` paths in [_layout.jade ](/ines/pretty-harp-jade-skeleton/blob/master/_layout.jade) and it should work again.

**Comment by moesphemie** [comment]
Yes! Thank you for clearing up the uncertainty :) I just should have tested it before asking you 🙈
